{% set name = "freud" %}
{% set version = "2.0.1" %}
{% set sha256 = "9fa803a6e7ae26dc8fb2e5717f1ee6aa09376c289eab3c0ce9d44352aeaed9b6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  script: "{{ PYTHON }} -m pip install . --ignore-installed --no-cache-dir -vv"
  skip: true  # [py<35]

requirements:
  build:
    - {{ compiler('cxx') }}

  host:
    - python
    - pip
    - cython
    - tbb
    - tbb-devel
    - numpy =1.14

  run:
    - python
    - tbb
    - {{ pin_compatible('numpy') }}
    - rowan >=1.2

test:
  imports:
    - freud

about:
  home: https://github.com/glotzerlab/{{ name }}
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'The freud Python library provides a simple, flexible, powerful set of tools for analyzing trajectories obtained from molecular dynamics or Monte Carlo simulations. High performance, parallelized C++ is used to compute standard tools such as radial distribution functions, correlation functions, order parameters, and clusters, as well as original analysis methods including potentials of mean force and torque (PMFTs) and local environment matching. The freud library uses NumPy arrays for input and output, enabling integration with the scientific Python ecosystem for many typical materials science workflows.'
  doc_url: http://{{ name }}.readthedocs.io/
  dev_url: https://github.com/glotzerlab/{{ name }}

extra:
  recipe-maintainers:
    - bdice
    - vyasr
    - joaander
