{% set name = "freud" %}
{% set version = "2.4.0" %}
{% set sha256 = "59f4d039e22d1e891c01adacd1e9d513f8538366a0694bcf925ef0bc9a7a597c" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/glotzerlab/{{ name }}/releases/download/v{{ version }}/{{ name }}-v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --ignore-installed --no-cache-dir -vv

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make  # [not win]

  host:
    - python
    - pip
    - cython
    - scikit-build
    - tbb
    - tbb-devel
    - numpy

  run:
    - python
    - tbb
    - {{ pin_compatible('numpy') }}
    - rowan >=1.2
    - scipy >=1.1

test:
  imports:
    - freud

about:
  home: https://github.com/glotzerlab/freud
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Powerful, efficient particle trajectory analysis in scientific Python.
  description: |
    The freud Python library provides a simple, flexible, powerful set of tools
    for analyzing trajectories obtained from molecular dynamics or Monte Carlo
    simulations. High performance, parallelized C++ is used to compute standard
    tools such as radial distribution functions, correlation functions, order
    parameters, and clusters, as well as original analysis methods including
    potentials of mean force and torque (PMFTs) and local environment matching.
    The freud library uses NumPy arrays for input and output, enabling
    integration with the scientific Python ecosystem for many typical materials
    science workflows.
  doc_url: https://freud.readthedocs.io/
  dev_url: https://github.com/glotzerlab/freud

extra:
  recipe-maintainers:
    - bdice
    - vyasr
    - joaander
