travis:
  secure:
    BINSTAR_TOKEN: b6Nbib1rZv2Js6tQZY9C9N+5l3zojHIutZCdEq85AaEpCPD5upMsOGw1LtcM4Z+muxUFIOrszd2LCcIre6o4rzOwmrwM2zxzxK8VnxIBQwLJl7BCTnW8Q2v8HLlwbSOoSy2M1OVM3paaxA7K5NjKdvpILm57udMGPbckVyTHj35oF/jmNi1rsrGHGP54vbMOTQVSswKxVUL7XNwBw6UkETLCBniHKr+fohcndtI/X2Jib7hQgNcV+Ks2zbmTGdywecpREB/4Y/AriUTtu9rXy5XXB2ugiaWHK+tScbtrshqNTunX6VAZQ/+JF9O+L5SeLiJt1vbw+/vsseEHW51jahjKKBbDZUXFko4ym5M67h3Vb0VP4oKLRmjMGxzky84Thl7/i3IPIvMDUMPRFV9hfs17vIpCzXyZEwJpRtT/4obCsw2UjhiUVtteYA8iiuy3U02hZi2ziixQfxQcsTawsgfbiEfkmkTrOGuJCMJ0Sec6sTk2XnjMhdPQKuHYZNpaWe7b+fqtXLew0ddidhoQDc9Ms/8rH1zqYWoFOflYXZYVk/gM4fsWajlth7j9K6EKNr8ATHHlIP5kR/zqAEnAPgkmzChafeBKT/MDg0C18Oc5rEsVg3PYaiZnYCZuauxhIr8MBokWic3LDt1rrhfradNmEUwNJMbj3yXDZ/lNB8Y=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
