appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
travis:
  secure:
    BINSTAR_TOKEN: j8NtzEW34Kdk57FLOpwp6c1b0+QgMQaYIH7u6VWixFaNb8UTMpUvOgMrhV3NRXu3S+tEUlmXlkBXgV0MU/DLjHulY3EBIJOjOjfeU99ihEBMuT1pM0481Ub2niZyQHji6vG58OU2NFK2LXnazVZ9IUgei2Bt+k8Nmlbcp8tf5FiaocZOxAXNcbjnucGH2uytA5wlZON+sw8F5qP/XZvRjsUOHZ2m/N6U9oL6YfvjsooLAzk9BgP7EiP3HdGx/U8ivlqfntUY13FV1Z7IiwLbeYnUxVCcQ3nMCjpaxM2J1cPFBoQoSF8KxOX3kd7UHFnBYUGVXHxaqZ5yxeNS0HObuUSrDHpRQJTXII/uUKq0JBU1bSzC+Q+MMYn50HkIDp5G+F25KbALPy7TqwnPkB6XUXgNot+CpvMRaNYFW1q25WAMVBJoVZ1sFdBVHE4fJMzRtBUlQi4ERy6ej1f0yEUrUbuoat9vpkK1Us/v4pswZ+9smQ3Uud90qQtLWMyttWA+JCvTztn7Cw1p2doXG9KiPJKMhKM7U/ra1V2Qu8jTmfPPm5mt2ygSIvPLlaZMKEdc09Bg9aG4XODwzNo4EK35PpnMbw1/Achjq9BszK+sJXR5mdYhaGmRt7t6IeGQUuq6VQA1p4Sa6QONflYyUy8705n0ofgQoxRECiwGQikvMW4=
provider:
  linux_ppc64le: default
  linux_aarch64: default
conda_forge_output_validation: true
